#+title: Adaptive Scoring for Elfeed
#+author: Dave Marquardt
#+email: daverrtx@gmail.com
#+OPTIONS: ':t toc:t author:t email:t
#+language: en
#+texinfo_filename: elfeed-score-adapt.info
#+texinfo_header: @syncodeindex pg cp
#+texinfo_dir_category: elfeed
#+texinfo_dir_name: elfeed-score-adapt
#+texinfo_printed_title: Adaptive Scoring for Elfeed

This manual is for Adaptive Scoring for Elfeed.

* What is Scoring for Elfeed?

Elfeed offers Gnus-style scoring to score articles based on various
attributes, including

- title
- authors
- feed URL

These are written into a score file, typically
@@texinfo:@file{elfeed.score}@@ in the user's Emacs directory,
typically @@texinfo:@file{~/.emacs.d}@@. They can be written manually
or through some interactive commands provided by the elfeed-score
package.

See @@texinfo:@xref{Scoring,,, gnus}@@ for more information on scoring
in Gnus.

See @@texinfo:@xref{,,, elfeed-score}@@ for more information on elfeed's
Gnus-style scoring.

* What is Adaptive Scoring for Elfeed?

Gnus also provides adaptive scoring, updating score entries based on
article attributes and user actions, like reading an article or
marking it as read.

This package brings adaptive scoring to Elfeed.

* How do I enable adaptive scoring for Elfeed?

To enable adaptive scoring for Elfeed, run this Emacs Lisp code:

#+begin_src emacs-lisp
(elfeed-score-adapt-enable)
#+end_src

If you want adaptive scoring enabled for every Emacs session, add the
code to your init file.

If you decide you want to stop adaptively scoring articles, run

#+begin_src emacs-lisp
(elfeed-score-adapt-disable)
#+end_src


* Adaptive Scoring Rules

Scoring rules are in src_emacs-lisp{elfeed-score-adapt-alist}. This is
an association list (alist). The keys are a user action. There are two
user actions defined:

- read: the user marks the article as read
- show: the user shows the article

The values are one or more lists of scores to set for the various
elements of the article. Only authors, feed, and title are supported
at this time.

The default value of src_emacs-lisp{elfeed-score-adapt-alist} is

#+begin_src emacs-lisp
  '((read
     (title -10))
    (show
     (authors 5)
     (feed 2)
     (title 30))
    )
#+end_src

Marking an article read will add -10 to the score for the article's
title, i.e.\nbsp{}an unfavorable score, since the user didn't want to
read it.

Showing an article will add 5 to the score for the authors, add 2 to
the score for the feed URL, and add 30 to the score for the title.
This favors this article's author, feed, and title for future scoring.

If you'd like different score values for the various elements, you can
set src_emacs-lisp{elfeed-score-adapt-alist} to your own prefered
values.

* Expiring adaptive score entries

After using adaptive scoring for a while, you'll have built up a large
number of score entries. You may want to stop using scores from a week
or so ago as the topics are stale, or maybe your reading interests
have changed in the meantime.

Adaptive score expiry will expire, i.e. remove, adaptive score entries
that are older than src_emacs-lisp{elfeed-score-adapt-expiry-days}
days old. The default value is 7 days.

To enable automatic expiry of old entries, run

#+begin_src emacs-lisp
(elfeed-score-adapt-expire-enable)
#+end_src

If you want to stop automatically expiring old entries, run

#+begin_src emacs-lisp
(elfeed-score-adapt-expire-disable)
#+end_src

If you'd just like to expire old entries manually, you can run

#+begin_src emacs-lisp
(elfeed-score-adapt-expire)
#+end_src


* Index
  :PROPERTIES:
  :INDEX:    cp
  :END:
